-- Supabase数据库结构
-- 创建作品表

-- 创建works表
CREATE TABLE IF NOT EXISTS works (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    brief TEXT NOT NULL,
    description TEXT NOT NULL,
    category TEXT[] NOT NULL,
    cover TEXT NOT NULL,
    ratio TEXT DEFAULT '16:9' CHECK (ratio IN ('16:9', '4:3')),
    "order" INTEGER NOT NULL DEFAULT 0,
    images TEXT[] DEFAULT '{}',
    videos TEXT[] DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 创建索引
CREATE INDEX IF NOT EXISTS works_order_idx ON works("order");
CREATE INDEX IF NOT EXISTS works_created_at_idx ON works(created_at DESC);

-- 启用行级安全
ALTER TABLE works ENABLE ROW LEVEL SECURITY;

-- 创建策略 - 允许所有人读取（用于前端展示）
CREATE POLICY "允许所有人读取作品"
    ON works
    FOR SELECT
    USING (true);

-- 创建策略 - 仅允许认证用户修改（用于后台管理）
CREATE POLICY "允许认证用户插入作品"
    ON works
    FOR INSERT
    WITH CHECK (auth.uid() IS NOT NULL);

CREATE POLICY "允许认证用户更新作品"
    ON works
    FOR UPDATE
    USING (auth.uid() IS NOT NULL);

CREATE POLICY "允许认证用户删除作品"
    ON works
    FOR DELETE
    USING (auth.uid() IS NOT NULL);

-- 创建存储桶用于图片上传（如果需要）
-- 在Supabase控制台创建一个名为 "portfolio-images" 的存储桶
-- 设置策略：允许所有人读取，仅认证用户上传

-- 插入一些示例数据
INSERT INTO works (title, brief, description, category, cover, ratio, "order", images, videos) VALUES
(
    '电商平台UI设计',
    '现代化电商平台UI设计，深色主题，流畅交互',
    '这是一个现代化的电商平台UI设计，注重用户体验和视觉美感。设计采用了深色主题，突出产品展示，同时保持界面简洁明了。主要功能包括商品浏览、搜索、购物车和结算流程，所有交互都经过精心设计，确保用户操作流畅自然。',
    ARRAY['UX设计', '品牌设计'],
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20e-commerce%20website%20UI%20design%20dark%20theme&image_size=landscape_16_9',
    '16:9',
    1,
    ARRAY[
        'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20e-commerce%20website%20UI%20design%20dark%20theme%20homepage&image_size=landscape_16_9',
        'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=modern%20e-commerce%20website%20UI%20design%20dark%20theme%20product%20page&image_size=landscape_16_9'
    ],
    ARRAY['https://player.bilibili.com/player.html?aid=12345678&bvid=BV12Z4y127VC&cid=123456789&page=1']
),
(
    '移动应用界面设计',
    '移动应用界面设计，深色主题，多模块功能',
    '这是一款移动应用的界面设计，采用深色主题，注重用户体验和视觉美感。应用包含多个功能模块，包括首页、消息、个人中心等，所有界面都经过精心设计，确保在移动设备上的显示效果和交互体验最佳。',
    ARRAY['UX设计'],
    'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mobile%20app%20UI%20design%20dark%20theme&image_size=portrait_4_3',
    '4:3',
    2,
    ARRAY[
        'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mobile%20app%20UI%20design%20dark%20theme%20home%20screen&image_size=portrait_4_3',
        'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=mobile%20app%20UI%20design%20dark%20theme%20profile%20screen&image_size=portrait_4_3'
    ],
    ARRAY[]
);

-- 创建updated_at自动更新函数
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- 创建updated_at自动更新触发器
CREATE TRIGGER update_works_updated_at BEFORE UPDATE ON works
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
